// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96MPjeplzX3YOtxtFSBwaM9MwZtejZhc',
    appId: '1:473124742575:web:cb9c95b87f0e815147fb5a',
    messagingSenderId: '473124742575',
    projectId: 'pushnotificationtesting-1aba8',
    authDomain: 'pushnotificationtesting-1aba8.firebaseapp.com',
    storageBucket: 'pushnotificationtesting-1aba8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pyQ13_LV278dPzClVc2d9QCmF3weDM4',
    appId: '1:473124742575:android:a36b021518d9986e47fb5a',
    messagingSenderId: '473124742575',
    projectId: 'pushnotificationtesting-1aba8',
    storageBucket: 'pushnotificationtesting-1aba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemxegSi1QGWBGynf2fQp0zCC6Sytj6iQ',
    appId: '1:473124742575:ios:3bdd5e4aba1b772e47fb5a',
    messagingSenderId: '473124742575',
    projectId: 'pushnotificationtesting-1aba8',
    storageBucket: 'pushnotificationtesting-1aba8.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemxegSi1QGWBGynf2fQp0zCC6Sytj6iQ',
    appId: '1:473124742575:ios:3bdd5e4aba1b772e47fb5a',
    messagingSenderId: '473124742575',
    projectId: 'pushnotificationtesting-1aba8',
    storageBucket: 'pushnotificationtesting-1aba8.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );
}
